services:
  pingauthorize:
    container_name: dpq-pingauthorize
    image: pingidentity/pingauthorize:edge
    ports:
      - "1389:1389/tcp"
      - "8443:1443/tcp"
    environment:
      SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
      SERVER_PROFILE_PATH: getting-started/pingauthorize 
      PING_IDENTITY_ACCEPT_EULA: YES 
    networks:
      localdev:
        aliases: 
        - pingauthorize.localdev
networks:
  localdev:
